name: "CI Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v7.0.0
      - name: Set up JDK
        uses: actions/setup-java@v5.5.0
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6.2.0
        with:
          build-scan-terms-of-use-url: https://gradle.com/terms-of-service
          build-scan-terms-of-use-agree: yes
      - run: "./gradlew build"
